### PR TITLE
Upgrade SonarLint language server and analyzers. Drop Scala and Ruby. Drop Windows.

### PR DESCRIPTION
**Pull request by necto**
Upgrade SonarLint language server and its analyzers to the newest versions:
- SonarLint language server 2.19.0
- HTML 3.7.1
- Java 7.14.0
- JavaScript & TypeScript 10.1.0
- PHP 3.28.0
- Python 4.2.0
- XML 2.7.0

New analyzers:
- Go 1.12.0
- Text (secrets + Unicode quirks) 2.0.1

Removed analyzers:
- Scala
- Ruby

Removed support for Windows.

Commentary:
Despite the smaller major version, 2.19.0 is the latest version of SonarLint language server, it is newer than 4.6.0. I don't know what happened with the versioning.
All the recent jars are published on the Maven or repox.jfrog.io instead of binaries.sonarsoruce.com

I decided to remove the support for Scala and Ruby because I was not able to make them work (old or new analyzers).

I removed the nominal support for Windows because I was not able to make it work. I suspect it never worked.
To make it work, you need to fix the mismatched assumptions about the line-ending used for the LSP separators between the "Content-Length: XX" header and the JSON content. According to my investigation, the `\r` characters are silently removed from the messages coming from the language server. I don't know how it is handled in other lsp-mode plugins.
Moreover, even after that fix, it seems that you need a Windows-specific SonarLint Language Server jar.
And even after using the one I found in VSCode extension, I was not able to make it work.
I am not sure it is worth the effort.

For both of the points above, I propose to wait for any user of Ruby or Scala, or Windows who is interested in
SonarLint for lsp-mode in Emacs.

### CODE REVIEW

**Comment by necto** [comment]
P.S., Even though I work for Sonar, this PR represents my personal interest that I pursued in my spare time. Any code or comments are my own and do not reflect Sonar's position.

**Comment by necto** [comment]
I've rearranged the commit history. Now each commit should be comprehensible, and you might want to merge the branch without squashing. Each commit [passes CI](https://github.com/necto/lsp-sonarlint/pull/1)

**Comment by necto** [comment]
Note that I returned nodejs install step, because it leads to more stable runs of JS/TS analyzer in the tests

**Review by jcs090218 — APPROVED** [review]
LGTM! However, I don't have push permission; let me ping some maintainers for you!

cc @yyoncho @Sasanidas

**Comment by necto** [comment]
Thank you, @jcs090218 !

**Comment by Sasanidas** [comment]
Thanks a lot, the code looks really good, but seems like some tests are failing with the error:
```
Parsing tar file...
Parsing tar file...done
Package ‘emacs-27.1’ is unavailable
make: *** [install] Error 1
Error: Process completed with exit code 2.
```

Which is kind of odd, maybe we can fix it before the merge?

**Comment by jcs090218** [comment]
@Sasanidas The error is from our side. #19 should fix it!

~~@necto Once #19 is merged, can you rebase this for us? The error should go away.~~

**Comment by Sasanidas** [comment]
Oh I see, then I'll merge this request, thanks a lot @necto  @jcs090218 :partying_face:

**Pull request merged**
